package(default_visibility = ["//water_simulator:__subpackages__"])

exports_files([
    "shader.vert",
    "shader.frag",
    "light_cube.fs",
    "light_cube.vs",
])

filegroup(
    name = "light_cube",
    srcs = [
        "light_cube.fs",
        "light_cube.vs",
    ],
)
