package(default_visibility = ["//water_simulator:__subpackages__"])

filegroup(
    name = "light_cube",
    srcs = [
        "light_cube.fs",
        "light_cube.vs",
    ],
)

filegroup(
    name = "simple",
    srcs = [
        "simple.fs",
        "simple.vs",
    ],
)

filegroup(
    name = "basic_lighting",
    srcs = [
        "basic_lighting.fs",
        "basic_lighting.vs",
    ],
)
